project:
  type: website

website:
  title: "mysite"
  navbar:
    navbar:
    title: "Kyungrok Park"
    left:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true

editor: visual

