project:
  type: website

website:
  title: "mysite"
  navbar:
    background: primary
    items:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: broadside
    toc: true

editor: visual

